#!/bin/bash

if [ "$1" = "clean" ]; then
rm -rf .build_lin/*
exit
fi

if [ "$1" = "cleanall" ]; then
rm -rf ./.build_lin/*
rm -rf ./.packages_lin/*
exit
fi

CFG=
if [ "${CONFIGURATION}" = "Release" ]; then
CFG=-c release
fi

BASE=`echo "${PROJECT_NAME}" | sed "s/ /_/g"`
RES=`docker run \
	-v "${PROJECT_DIR}:/perfectbuild" \
	-v "${PROJECT_DIR}/.packages_lin:/perfectbuild/Packages" \
	-w /perfectbuild \
	--name ${BASE} \
	--rm \
	-t \
	badthing/perfectassistant \
	swift build --build-path=/perfectbuild/.build_lin ${CFG}`
CNT=`echo "${RES}" | egrep -c ":\d+:\d+:"`
if [ ${CNT} != "0" ];
then
echo "${RES}" | egrep ":\d+:\d+:" | sed 's|'${PREFIX}/'||'
exit -1
fi
